config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  
  get 'home/top'
  get 'home/tfdiary'
  get 'home/terms'
  get 'home/questions'

  devise_for :users, :skip => [:registration], controllers: {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  resources :users, :only => [:show] do
    collection do
      patch :change_image
      get :follow_menu
      get :unfollow_menu
      get :follow_user
      get :unfollow_user
      get :follow_diary
      get :unfollow_diary
      get :unregist_confirm
      post :unregist
    end
    
    member do
      get :follow_index
      get :follower_index
      get :menu_index
      get :group_index
      get :regist_menu
      get :set_main_group
    end
    
    resources :diaries, shallow: true do
      collection do
        post :save_diary_all
        get :add_all_menu
        post :regist_menus
        post :save_diary_group
        get :select_group_menu
        get :read_group_menu
      end
      
      member do
        get :favoriter_index
      end
      
      resources :comments, :only => [:create, :destroy]
    end
  end

  resources :menus do
    collection do
      get :search
    end
    
    member do
      get :register_index
    end
  end

  resources :groups do
    collection do
      get :search
    end
    
    member do
      post :follow
      patch :follow_cancel
      patch :change_image
    end
    
    resources :group_member, :only => [:index], shallow: true do
      member do
        get :top
        get :setting
        get :menu_status
        get :request_index
        post :post_chat
        get :delete_chat
        get :assign_job
        patch :change_job
        post :follow_approve
        post :follow_reject
        get :unfollow_confirm
        get :unfollow
      end
    end
    
    resources :group_diaries do
      collection do
        post :add_all_menu
        post :regist_menus
      end
    end
  end

  get 'contacts/input'
  post 'contacts/confirm'
  post 'contacts/send_msg'

end

app/models/diary.rb
class Diary < ActiveRecord::Base
    acts_as_followable
    
    belongs_to :user
    belongs_to :group
    has_many :comments, dependent: :destroy
    has_many :diary_menus, dependent: :destroy
    accepts_nested_attributes_for :diary_menus, allow_destroy: true, reject_if: :all_blank
    
    validates :title, :presence => true, :if => :not_temp?
    validates :user_id_or_group_id, :presence => true
    validates :date, :presence => true, :if => :not_temp?
    
private
    def user_id_or_group_id
        user_id.presence or group_id.presence
    end

    def not_temp?
        !temp
    end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!
  before_action :delete_tmp, except: [:add_all_menu, :regist_menus, :select_group_menu, :read_group_menu]

  def new
    @user = User.find(params[:user_id])
    @diary = @user.diaries.build
    @menu_list = get_menu_list(@user)
  end
  
  def create
    @user = User.find(params[:user_id])
    if view_context.current_user.id == @user.id
      @diary = @user.diaries.build(diary_params)
      if @diary.save
        create_notice(@user, @diary.id)
        redirect_to diary_path(@diary.id)
      else
        @menu_list = get_menu_list(@user)
        render :new
      end
    else
      redirect_to user_path(@user.id)
    end
  end

  def edit
    @diary = Diary.find(params[:id])
    @user = User.find(@diary.user_id)
    @menu_list = get_menu_list(@user)
  end
  
  def update
    @diary = Diary.find(params[:id])
    @user = User.find(@diary.user_id)
    if @diary.user_id == @user.id
      if @diary.update(diary_params)
        redirect_to user_diaries_path(@user.id)
      else
        @menu_list = get_menu_list(@user)
        render :edit
      end
    else
      redirect_to user_diaries_path(@user.id)
    end
  end

  def destroy
    @diary = Diary.find(params[:id])
    if view_context.current_user.id == @diary.user_id
      @diary.destroy
    end
    redirect_to user_diaries_path(@diary.user_id)
  end
  
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @diary = Diary.find(params[:id])
    @comments = @diary.comments
    @comment = Comment.new
  end
  
  def save_diary_all
    @user = User.find(params[:user_id])
    set_diary_temp(@user)
    redirect_to add_all_menu_user_diaries_path(@user.id)
  end

  def add_all_menu
    @user = User.find(params[:user_id])
    @menus_run = @user.following_menus.where(:kind => Menu.kinds[:run])
    @menus_jump = @user.following_menus.where(:kind => Menu.kinds[:jump])
    @menus_throw = @user.following_menus.where(:kind => Menu.kinds[:throw])
    @menus_drill = @user.following_menus.where(:kind => Menu.kinds[:drill])
    @menus_other = @user.following_menus.where(:kind => Menu.kinds[:other])
  end
  
  def regist_menus
    @user = User.find(params[:user_id])
    @diary = @user.diaries.find_by(temp: true)
    get_check_menu(@user, @diary)
    @menu_list = get_menu_list(@user)
    render :new
  end

  def save_diary_group
    @user = User.find(params[:user_id])
    set_diary_temp(@user)
    redirect_to select_group_menu_user_diaries_path(@user.id)
  end

  def select_group_menu
    @user = User.find(params[:user_id])
    unless @user.main_group_id.nil?
      @group = Group.find(@user.main_group_id)
    else
      flash[:alert] = "メイングループが設定されていません"
      @diary = @user.diaries.find_by(temp: true)
      @menu_list = get_menu_list(@user)
      render :new
    end
  end

  def read_group_menu
    @user = User.find(params[:user_id])
    @diary = @user.diaries.find_by(temp: true)
    @menu_list = get_menu_list(@user)
    diary_menu_copy(@diary, @menu_list)
    render :new
  end

  def favoriter_index
    @diary = Diary.find(params[:id])
    @favoriters = @diary.user_followers.page(params[:page]).per(20)
  end
  
private
  def diary_params
    params.require(:diary).permit(
      :title,
      :date,
      :explain,
      diary_menus_attributes: [:id, :menu_id, :num, :set, :rest_min, :rest_sec, :_destroy]
    )
  end

  def delete_tmp
    tmp = view_context.current_user.diaries.find_by(temp: true)
    unless tmp.nil?
      tmp.destroy
    end
  end

  def get_menu_list(user)
    menu_list = Hash.new
    menus = user.following_by_type('Menu')
    menus.each do |menu|
      menu_list[menu.name] = menu.id
    end
    
    return menu_list
  end
  
  def get_check_menu(user, diary)
    menus = user.following_by_type('Menu')
    menus.each do |menu|
      if params[:menu]["#{menu.id}"]
        diary.diary_menus.build(:menu_id => menu.id,
                                :num => 0,
                                :set => 0,
                                :rest_min => 0,
                                :rest_sec => 0)
      end
    end
  end
  
  def diary_menu_copy(diary, menu_list)
    diary_org = Diary.find(params[:diary_id])
    diary_org.diary_menus.each do |diary_menu|
      diary.diary_menus.build(:menu_id => diary_menu.menu_id,
                              :num => diary_menu.num,
                              :set => diary_menu.set,
                              :rest_min => diary_menu.rest_min,
                              :rest_sec => diary_menu.rest_sec)
      
      menu = Menu.find(diary_menu.menu_id)
      if !menu_list.has_key?(menu.name)
        menu_list[menu.name] = menu.id
      end
    end
  end

  def set_diary_temp(user)
    diary_temp = user.diaries.build(diary_params)
    diary_temp.temp = true
    diary_temp.save
  end

  # フォロワーへ日誌生成通知
  def create_notice(user, diary_id)
    user.user_followers.each do |follower|
      latest = follower.notices.order(created_at: :desc).first
      notice = follower.notices.build()
      notice.create_user_diary(user, diary_path(diary_id))
      unless latest&.msg == notice.msg
        notice.save
      end
    end
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
    def get_diary(user, date)
        user.diaries.where(:date => date)
    end
    
    def get_menu(id)
        Menu.find(id)
    end
    
    def get_user(id)
        User.find(id)
    end
end

app/views/diaries/_diary_menu_fields.html.erb
<div id="diary-menu-table">
<table class="table table-bordered table-hover table-font">
    <thead>
        <tr class="table-primary">
           <th>メニュー名</th>
           <th>回数/セット数</th>
           <th>レスト 分/秒</th>
           <th></th>
        </tr>
    </thead>
    <tbody id="sortdata">
        <%= f.nested_fields_for :diary_menus, wrapper_tag: :tr do |q| %>
            <!--メニュー名-->
            <td class="sortable-handle">
                <%= q.select :menu_id, @menu_list, class: 'form-control' %>
            </td>
            <!--回数/セット-->
            <td>
                <div class="column-field">
                    <%= q.number_field :num, :min => 0, class: 'form-control' %>
                </div>
                <div class="column-unit">
                    回
                </div>
                <div class="column-field">
                    <%= q.number_field :set, :min => 0, class: 'form-control' %>
                </div>
                <div class="column-unit">
                    セット
                </div>
            </td>
            <!--レスト分/秒-->
            <td>
                <div class="column-field">
                    <%= q.number_field :rest_min, :min => 0, class: 'form-control' %>
                </div>
                <div class="column-unit">
                    分
                </div>
                <div class="column-field">
                    <%= q.number_field :rest_sec, :min => 0, class: 'form-control' %>
                </div>
                <div class="column-unit">
                    秒
                </div>
            </td>
            <td><%= q.remove_nested_fields_link '削除', class: 'btn btn-danger', role: 'button' %></td>
        <% end %>
    </tbody>
</table>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
<script type="text/javascript">
    jQuery(function($) {
        $('#sortdata').sortable({handle: ".sortable-handle"});
    });
</script>

<%= f.add_nested_fields_link :diary_menus, 'メニュー追加', class: 'btn btn-primary', role: 'button' %>
</div>

app/views/diaries/_error_notice.html.erb
<div class="error_notice">
<% if nil != @diary %>
  <% if @diary.errors.any? %>
    <div class="error_explanation">
      <ul style="list-style:none;">
      <% @diary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
</div>

app/views/diaries/_menu_index_part.html.erb
<ul class="list-group list-group-flush">
<% if menus.count == 0 %>
    <li class="list-group-item">
        登録メニューがありません。
    </li>
<% else %>
    <% menus.each do |menu| %>
        <li class="list-group-item">
            <%= check_box_tag "menu[#{menu.id}]" %>
            <% if (current_user != menu.author_id) && (true == menu.secret) %>
                <%= menu.name %>
            <% else %>
                <%= link_to menu.name, menu_path(menu.id) %>
            <% end %>
        </li>
    <% end %>
<% end %>
</ul>

app/views/diaries/_show_menu.html.erb
<ul class="list-unstyled">
<% diary.diary_menus.each do |diary_menu| %>
    <% menu = get_menu(diary_menu.menu_id) %>
    <li>
        <% if (current_user != menu.author_id) && (true == menu.secret) %>
            <%= menu.name %>
        <% else %>
            <%= link_to menu.name, menu_path(menu.id) %>
        <% end %>
        <% if menu.drill? %>
            <%= diary_menu.num.to_s %> 回
        <% else %>
            <%= diary_menu.num.to_s %> 本
        <% end %>
        <%= diary_menu.set.to_s %> セット
        Rest
        <%= diary_menu.rest_min %> 分
        <%= diary_menu.rest_sec %> 秒
    </li>
<% end %>
</ul>

app/views/diaries/add_all_menu.html.erb
<h2>メニュー一括追加</h2>
<div class="add-menu-link">
    <%= link_to "新規メニュー追加", new_menu_path, :class => "btn btn-primary" %>
    &emsp;
    <%= link_to "メニューを検索して登録", menus_path, :class => "btn btn-primary" %>
</div>
<%= form_tag regist_menus_user_diaries_path(@user.id), :method => :post do %>
<div id="menu-index">
    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#run-menu" role="button" aria-expanded="true" aria-controls="run-menu">走</a>
        </div>
        <div class="collapse" role="tabpanel" id="run-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="true">
            <%= render "diaries/menu_index_part", :menus => @menus_run %>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#jump-menu" role="button" aria-expanded="false" aria-controls="jump-menu">跳</a>
        </div>
        <div class="collapse" role="tabpanel" id="jump-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
            <%= render "diaries/menu_index_part", :menus => @menus_jump %>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#throw-menu" role="button" aria-expanded="false" aria-controls="throw-menu">投</a>
        </div>
        <div class="collapse" role="tabpanel" id="throw-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
            <%= render "diaries/menu_index_part", :menus => @menus_throw %>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#drill-menu" role="button" aria-expanded="false" aria-controls="drill-menu">補強・サーキット</a>
        </div>
        <div class="collapse" role="tabpanel" id="drill-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
            <%= render "diaries/menu_index_part", :menus => @menus_drill %>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#other-menu" role="button" aria-expanded="false" aria-controls="other-menu">その他</a>
        </div>
        <div class="collapse" role="tabpanel" id="other-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
            <%= render "diaries/menu_index_part", :menus => @menus_other %>
        </div>
    </div>
</div>
<div class="menu-add-submit">
    <%= submit_tag "一括追加", :class => "btn btn-success" %>
</div>
<% end %>

app/views/diaries/edit.html.erb
<h2>日誌編集</h2>
<br>

<%= render "diaries/error_notice" %>

<div class="diary-create">
    <%= form_for @diary, :url => {:action => 'update'} do |f| %>
        <%= f.label :title, "タイトル", :class => "diary-label" %>
        <br>
        <%= f.text_field :title, :size => "40" %>
        <br>
        <%= f.label :date, "日付", :class => "diary-label" %>
        <br>
        <%= f.date_field :date %>
        <br>
        <%= label :menu, "メニュー", :class => "diary-label" %>
        <br>
        <%= render "diaries/diary_menu_fields", f: f %>
        <br>
        <%= f.label :explain, "説明", :class => "diary-label" %>
        <br>
        <%= f.text_area :explain, :size => "40x10", :class => "dialy-explain-input" %>
        <br>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.submit "更新", :class => "btn btn-success" %>
    <% end %>
</div>

app/views/diaries/favoriter_index.html.erb
<h3 class="pt-2"><%= link_to @diary.title, diary_path(@diary.id) %>にいいねした人</h3>

<div class="diary-favoriter">
    <%= render "page_counter", :models => @favoriters %>
    <ul class="list-group">
        <% @favoriters.each do |favoriter| %>
            <li class="list-group-item">
                <%= image_tag favoriter.image, :size => "50x50", :class => "rounded-circle" %>
                &emsp;
                <%= link_to favoriter.name, user_path(favoriter.id) %>
            </li>
        <% end %>
    </ul>
</div>

<div class="my-pagenate clearfix">
    <%= paginate @favoriters %>
</div>

app/views/diaries/index.html.erb
<div class="user-show-body">
  <%= render "users/user_header", :user => @user, :diaries => get_diaries(@user) %>
  <%= render "users/user_nav", :user => @user %>
  <div class="user-notice div-center">
    <div class="my-3">
      <%= link_to "日誌を作成", new_user_diary_path, :class => "btn btn-primary" %>
    </div>
    <%= month_calendar do |date| %>
      <% diaries = get_diary(@user, date) %>
      <%= date.day %>
      <br>
      <% if 0 != diaries.count %>
        <% diaries.each do |diary| %>
            <%= link_to diary.title, diary_path(diary.id)  %>
            <br>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/diaries/new.html.erb
<h2>日誌作成</h2>
<br>

<%= render "diaries/error_notice" %>

<div class="diary-create">
    <%= form_for @diary, :url => {:action => 'create'}, :method => "POST" do |f| %>
        <%= f.label :title, "タイトル", :class => "diary-label" %>
        <br>
        <%= f.text_field :title, :size => "40" %>
        <br>
        <%= f.label :date, "日付", :class => "diary-label" %>
        <br>
        <%= f.date_field :date %>
        <br>
        <%= label :menu, "メニュー", :class => "diary-label" %>
        <br>
        <button class="btn btn-primary" type="button" onClick="submitAction('<%= save_diary_all_user_diaries_path(@user.id) %>');">メニューの一括追加</button>
        &emsp;
        <button class="btn btn-primary" type="button" onClick="submitAction('<%= save_diary_group_user_diaries_path(@user.id) %>');">グループメニューから読み込み</button>
        <%= render "diaries/diary_menu_fields", f: f %>
        <br>
        <%= f.label :explain, "説明", :class => "diary-label" %>
        <br>
        <%= f.text_area :explain, :size => "40x10", :class => "dialy-explain-input" %>
        <br>
        <%= f.submit "作成", :class => "btn btn-success" %>
    <% end %>
</div>

app/views/diaries/select_group_menu.html.erb
<h3><%= @group.name %>のメニューから追加</h3>
<br>

<div id="index_calender_area" class="w-75 mx-auto text-center">
    <div id="index_calender">
    <%= month_calendar do |date| %>
      <% diaries = get_diary_group(@group, date) %>
      <%= date.day %>
      <br>
      <% if 0 != diaries.count %>
        <% diaries.each do |diary| %>
            <%= link_to diary.title, read_group_menu_user_diaries_path(@user.id, :diary_id => diary.id)  %>
            <br>
        <% end %>
      <% end %>
    <% end %>
    </div>
</div>

<%= render "group_member/return_link", id: @group.id %>

app/views/diaries/show.html.erb
<h2>
    <%= @diary.date.year %> 年
    <%= @diary.date.month %> 月
    <%= @diary.date.day %> 日
    &ensp;
    <%= @diary.title %>
</h2>
<% if current_user.id == @diary.user_id %>
    <div id="diary-edit-link">
        <%= link_to "編集", edit_diary_path(@diary.id) %>
        &ensp;
        <%= link_to "削除", diary_path(@diary.id), :method => :delete, :data => {:confirm => "本当に削除しますか？"} %>
    </div>
<% end %>
<div id="diary-detail">
    <div class="diary-column">
        メニュー内容
    </div>
    <div id="diary-detail-menu">
        <%= render "diaries/show_menu", diary: @diary %>
    </div>
    <div class="diary-column">
        説明
    </div>
    <div id="diary-detail-explain">
        <%= simple_format(@diary.explain) %>
    </div>
</div>

<div id="diary-favorite">
    <% if current_user.following?(@diary) %>
    <div id="diary-favo" class="diary-unfavorite-button" onClick="OnClickDiaryFavorite(<%= @diary.id %>);">
    <% else %>
    <div id="diary-favo" class="diary-favorite-button" onClick="OnClickDiaryFavorite(<%= @diary.id %>);">
    <% end %>
    いいね！
    </div>
    <div id="diary-favorite-count">
        <%= link_to "#{@diary.user_followers.count}件", favoriter_index_diary_path(@diary.id), :id => "diary-favorite-count-link" %>
    </div>
</div>
<div class="clear"></div>
<div id="diary-comment">
    コメント
    <%= form_for @comment, :url => diary_comments_path(@diary.id) do |f| %>
        <%= f.text_area :content, :size => "40x3", :class => "dialy-comment-input" %>
        <br>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.submit "投稿", :class => "btn btn-primary" %>
    <% end %>

    <% if 0 == @comments.count %>
        <div id="comment-index-title">コメントはありません</div>
    <% else %>
        <div id="comment-index-title">コメント一覧</div>
        <div id="comment-index">
            <ul>
            <% @comments.each do |comment| %>
                <% user = get_user(comment.user_id) %>
                <li>
                    <%= image_tag user.image, :class => "commenter-img" %> &ensp; <%= link_to user.name, user_path(user.id) %>
                    <% if user.id == current_user.id %>
                        &emsp;
                        <%= link_to "コメント削除", comment_path(comment.id), :method => 'DELETE' %>
                    <% end %>
                    <div class="comment-content">
                        <%= simple_format(comment.content) %>
                    </div>
                </li>
            <% end %>
            </ul>
        </div>
    <% end %>
</div>