config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  
  get 'home/top'
  get 'home/tfdiary'
  get 'home/terms'
  get 'home/questions'

  devise_for :users, :skip => [:registration], controllers: {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  resources :users, :only => [:show] do
    collection do
      patch :change_image
      get :follow_menu
      get :unfollow_menu
      get :follow_user
      get :unfollow_user
      get :follow_diary
      get :unfollow_diary
      get :unregist_confirm
      post :unregist
    end
    
    member do
      get :follow_index
      get :follower_index
      get :menu_index
      get :group_index
      get :regist_menu
      get :set_main_group
    end
    
    resources :diaries, shallow: true do
      collection do
        post :save_diary_all
        get :add_all_menu
        post :regist_menus
        post :save_diary_group
        get :select_group_menu
        get :read_group_menu
      end
      
      member do
        get :favoriter_index
      end
      
      resources :comments, :only => [:create, :destroy]
    end
  end

  resources :menus do
    collection do
      get :search
    end
    
    member do
      get :register_index
    end
  end

  resources :groups do
    collection do
      get :search
    end
    
    member do
      post :follow
      patch :follow_cancel
      patch :change_image
    end
    
    resources :group_member, :only => [:index], shallow: true do
      member do
        get :top
        get :setting
        get :menu_status
        get :request_index
        post :post_chat
        get :delete_chat
        get :assign_job
        patch :change_job
        post :follow_approve
        post :follow_reject
        get :unfollow_confirm
        get :unfollow
      end
    end
    
    resources :group_diaries do
      collection do
        post :add_all_menu
        post :regist_menus
      end
    end
  end

  get 'contacts/input'
  post 'contacts/confirm'
  post 'contacts/send_msg'

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :image, UserImagesUploader
  acts_as_followable
  acts_as_follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  
  has_many :diaries, dependent: :destroy
  has_many :notices, dependent: :destroy
  
  validates :name, :presence => true, :uniqueness => true
  
  def soft_delete
    update(deleted_at: Time.now)
  end
  
  def active_for_authentication?
    super && !deleted_at
  end
  
  def inactive_message
    !deleted_at ? super : :deleted_account
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    user = User.find_by(:email => params[:user][:email])
    if (!user.nil?) && (!user.active_for_authentication?)
      user.destroy
    end

    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_current_user, :only => [:show]
  
  def show
    @user = User.find(params[:id])
    @notices = @user.notices.order(created_at: :desc).page(params[:page]).per(20)
  end

  def follow_index
    @user = User.find(params[:id])
    @follows = @user.following_users.page(params[:page]).per(20)
  end

  def follower_index
    @user = User.find(params[:id])
    @followers = @user.user_followers.page(params[:page]).per(20)
  end
  
  def menu_index
    @user = User.find(params[:id])
    @menus = @user.following_menus
    @menus_run = @menus.where(:kind => Menu.kinds[:run])
    @menus_jump = @menus.where(:kind => Menu.kinds[:jump])
    @menus_throw = @menus.where(:kind => Menu.kinds[:throw])
    @menus_drill = @menus.where(:kind => Menu.kinds[:drill])
    @menus_other = @menus.where(:kind => Menu.kinds[:other])
  end

  def group_index
    @user = User.find(params[:id])
    @groups = @user.following_groups.page(params[:page]).per(20)
  end
  
  def change_image
    @user = User.find(view_context.current_user.id)
    @user.image = params[:user][:image]
    @user.save
    redirect_to user_path(@user.id)
  end
  
  def follow_menu
    menu = Menu.find(params[:menu_id])
    view_context.current_user.follow(menu)
    render :nothing => true
  end
  
  def unfollow_menu
    menu = Menu.find(params[:menu_id])
    view_context.current_user.stop_following(menu)
    render :nothing => true
  end

  def follow_user
    user = User.find(params[:user_id])
    view_context.current_user.follow(user)
    create_follow_notice(view_context.current_user, user)
    render :nothing => true
  end
  
  def unfollow_user
    user = User.find(params[:user_id])
    view_context.current_user.stop_following(user)
    render :nothing => true
  end
  
  def follow_diary
    diary = Diary.find(params[:diary_id])
    view_context.current_user.follow(diary)
    create_follow_notice(view_context.current_user, diary)
    render :nothing => true
  end
  
  def unfollow_diary
    diary = Diary.find(params[:diary_id])
    view_context.current_user.stop_following(diary)
    render :nothing => true
  end
  
  def set_main_group
    user = User.find(params[:id])
    user.update(:main_group_id => params[:group_id])
    redirect_to group_index_user_path(user.id)
  end
  
  def unregist_confirm
  end
  
  def unregist
    user = view_context.current_user
    if user.valid_password?(params[:password])
      # グループリーダーでない場合のみ退会可能
      if !view_context.group_leader?(user.id)
        group_auth_delete(user.id)
        user.soft_delete
        sign_out(user)
        redirect_to root_path
      else
        flash[:alert] = "所属しているグループのリーダーとなっています"
        redirect_to unregist_confirm_users_path
      end
    end
  end
  
private
  def check_current_user
    unless view_context.current_user.id == params[:id].to_i
      redirect_to user_diaries_path(params[:id])
    end
  end

  # フォロー時の通知
  def create_follow_notice(user, follow)
    latest = follow.notices.order(created_at: :desc).first
    notice = follow.notices.build()
    notice.create_user_favorite(user, user_path(user.id))
    unless latest&.msg == notice.msg
      notice.save
    end
  end
  
  # 日誌いいね時の通知
  def create_diary_notice(user, diary)
    diuser = User.find(diary.user_id)
    latest = diuser.notices.order(created_at: :desc).first
    notice = diuser.notices.build()
    notice.create_diary_favorite(user, diary_path(diary_id))
    unless latest&.msg == notice.msg
      notice.save
    end
  end
  
  # 退会時のグループ管理者権限削除
  def group_auth_delete(user_id)
    groups = Group.where(:subleader_id1 => user_id)
    groups.each do |group|
      group.update(subleader_id1: nil)
    end
    
    groups = Group.where(:subleader_id2 => user_id)
    groups.each do |group|
      group.update(subleader_id2: nil)
    end
    
    groups = Group.where(:subleader_id3 => user_id)
    groups.each do |group|
      group.update(subleader_id3: nil)
    end
    
    groups = Group.where(:manager_id1 => user_id)
    groups.each do |group|
      group.update(manager_id1: nil)
    end
    
    groups = Group.where(:manager_id2 => user_id)
    groups.each do |group|
      group.update(manager_id2: nil)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def get_user(id)
    User.find(id)
  end
    
  def get_diaries(user)
    diaries = []
    if user.main_group_id
      group = Group.find(user.main_group_id)
      diaries = group.diaries.where(:date => Time.now.strftime("%Y-%m-%d"))
    else
      diaries = user.diaries.where(:date => Time.now.strftime("%Y-%m-%d"))
    end
    
    return diaries
  end
end

app/views/users/_error_notification.html.erb
<% if nil != @user %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul style="list-style:none;">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/users/_menu_index_part.html.erb
<ul class="list-group list-group-flush">
<% if menus.count == 0 %>
    <li class="list-group-item">
        登録メニューがありません。
    </li>
<% else %>
    <% menus.each do |menu| %>
        <li class="list-group-item">
            <% if (current_user != menu.author_id) && (true == menu.secret) %>
                <%= menu.name %>
            <% else %>
                <%= link_to menu.name, menu_path(menu.id) %>
            <% end %>
        </li>
    <% end %>
<% end %>
</ul>

app/views/users/_timeline.html.erb
<ul class="list-group list-unstyled">
    <% notices.each do |notice| %>
        <li class="list-group-item">
            <% if notice.image_path %>
                <%= image_tag notice.image_path, :size => "30x30", :class => "rounded-circle" %>
                &ensp;
            <% end %>
            <%= link_to notice.msg, notice.link %>
        </li>
    <% end %>
</ul>

app/views/users/_user_header.html.erb
<div class="user-profile div-center clearfix">
    <div class="user-image div-center float-left">
      <% if current_user.id == user.id %>
        <br>
        <%= form_for user, :url => change_image_users_path, :html => {method: 'PATCH'} do |f| %>
          <%= f.label :image, :class => "ignore" %>
          <label for="user_image" class="image-select">
            <%= image_tag user.image.url, :size => "150x150" %>
            <%= f.file_field :image, :class => "ignore" %>
          </label>
        <% end %>
        <script type="text/javascript">
            $('input[type=file]').on('change', function (e) {
                console.log(e.target.files);
                if (e.target.files[0].size > 0) {
                    $(this).parents('form').submit();
                }
            });
        </script>
        <p><%= user.name %></p>
      <% else %>
        <%= image_tag user.image, :size => "150x150" %>
        <p><%= user.name %></p>
        <% if current_user.following?(@user) %>
            <div id="user-follow-button" class="unfollow" onclick="OnClickFollowUser(<%= @user.id %>);">
                フォロー解除
            </div>
        <% else %>
            <div id="user-follow-button" class="follow" onclick="OnClickFollowUser(<%= @user.id %>);">
                フォロー
            </div>
        <% end %>
      <% end %>
    </div>
    <div class="user-info div-center float-left">
      <div class="text-left">
      <% if user.main_group_id %>
        所属グループ：<%= link_to get_group(user.main_group_id).name, top_group_member_path(get_group(user.main_group_id).id) %>
      <% else %>
        所属グループ：なし
      <% end %>
      </div>
      
      <div class="user-practice div-center">
          <div class="text-left">今日の練習メニュー</div>
          <div class="practice-box div-center">
              <div class="group-member-todaymenu-box">
                  <% if diaries.count == 0 %>
                    登録無し
                  <% end %>
                  <% diaries.each do |diary| %>
                      <div class="group-todaymenu">
                          <%= link_to diary.title, group_group_diary_path(diary.group_id, diary.id) %>
                          <%= render "diaries/show_menu", diary: diary %>
                      </div>
                  <% end %>
              </div>
          </div>
      </div>
    </div>
</div>

app/views/users/_user_nav.html.erb
<ul class="nav nav-tabs">
  <% if current_user.id == user.id %>
    <li class="nav-item">
      <%= link_to "お知らせ", user_path(user.id), :class => "nav-link #{active_action?('show')}" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "練習日誌", user_diaries_path(user.id), :class => "nav-link #{active_action?('index')}" %>
  </li>
  <li class="nav-item">
    <%= link_to "メニュー", menu_index_user_path(user.id), :class => "nav-link #{active_action?('menu_index')}" %>
  </li>
  <li class="nav-item">
    <%= link_to "フォロー", follow_index_user_path(user.id), :class => "nav-link #{active_action?('follow_index')}" %>
  </li>
  <li class="nav-item">
    <%= link_to "フォロワー", follower_index_user_path(user.id), :class => "nav-link #{active_action?('follower_index')}" %>
  </li>
  <li class="nav-item">
    <%= link_to "グループ", group_index_user_path(user.id), :class => "nav-link #{active_action?('group_index')}" %>
  </li>
  <% if current_user.id == user.id %> 
  <li class="nav-item">
    <%= link_to "設定", edit_user_registration_path(user.id), :class => "nav-link #{active_action?('edit')}" %>
  </li>
  <% end %>
</ul>

app/views/users/follow_index.html.erb
<div class="user-show-body">
  <%= render "users/user_header", :user => @user, :diaries => get_diaries(@user) %>
  <%= render "users/user_nav", :user => @user %>
  <div class="user-notice div-center">
    <div id="follow-index">
      <ul class="list-group">
      <% @follows.each do |follow| %>
        <li class="list-group-item">
            <%= image_tag follow.image, :size => "50x50", :class => "rounded-circle" %>
            &emsp;
            <%= link_to follow.name, user_path(follow.id) %>
        </li>
      <% end %>
    </div>
    
    <div class="my-pagenate w-75 clearfix">
      <div class="float-left">
        <%= render "page_counter", :models => @follows %>
      </div>
      <div class="float-right">
        <%= paginate @follows %>
      </div>
    </div>
  </div>
</div>

app/views/users/follower_index.html.erb
<div class="user-show-body">
  <%= render "users/user_header", :user => @user, :diaries => get_diaries(@user) %>
  <%= render "users/user_nav", :user => @user %>
  <div class="user-notice div-center">
    <div id="follower-index">
      <ul class="list-group">
      <% @followers.each do |follower| %>
        <li class="list-group-item">
            <%= image_tag follower.image, :size => "50x50", :class => "rounded-circle" %>
            &emsp;
            <%= link_to follower.name, user_path(follower.id) %>
        </li>
      <% end %>
    </div>
    
    <div class="my-pagenate w-75 clearfix">
      <div class="float-left">
        <%= render "page_counter", :models => @followers %>
      </div>
      <div class="float-right">
        <%= paginate @followers %>
      </div>
    </div>
  </div>
</div>

app/views/users/group_index.html.erb
<div class="user-show-body">
  <%= render "users/user_header", :user => @user, :diaries => get_diaries(@user) %>
  <%= render "users/user_nav", :user => @user %>
  <div class="user-notice mt-3">
    <%= link_to "新規グループ作成", new_group_path, :class => "btn btn-primary" %>

    <div id="group-index">
      <ul class="list-group">
      <% @groups.each do |group| %>
        <li class="list-group-item">
          <%= image_tag group.image, :size => "50x50", :class => "rounded-circle" %>
          &emsp;
          <%= link_to group.name, top_group_member_path(group.id) %>
          &emsp;
          <% if @user.main_group_id == group.id %>
              メイン所属グループ
          <% end %>
          <% if @user.id == current_user.id %>
            <% if @user.main_group_id != group.id %>
              <%= link_to "メイングループに設定", set_main_group_user_path(@user.id, :group_id => group.id), :class => "btn btn-primary" %>
            <% end %>
            &emsp;
            <%= link_to "グループから抜ける", unfollow_confirm_group_member_path(group.id), :class => "btn btn-primary" %>
          <% end %>
        </li>
      <% end %>
    </div>

    <div class="my-pagenate w-75 clearfix">
      <div class="float-left">
        <%= render "page_counter", :models => @groups %>
      </div>
      <div class="float-right">
        <%= paginate @groups %>
      </div>
    </div>
  </div>
</div>

app/views/users/menu_index.html.erb
<div class="user-show-body">
  <%= render "users/user_header", :user => @user, :diaries => get_diaries(@user) %>
  <%= render "users/user_nav", :user => @user %>
  <div class="user-notice">
    <div class="my-3">
      <%= link_to "新規メニュー作成", new_menu_path, :class => "btn btn-primary" %>
    </div>
    
    登録メニュー数(<%= @menus.count %>)
    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#run-menu" role="button" aria-expanded="true" aria-controls="run-menu">走</a>
        </div>
        <div class="collapse" role="tabpanel" id="run-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="true">
            <%= render "users/menu_index_part", :menus => @menus_run %>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#jump-menu" role="button" aria-expanded="false" aria-controls="jump-menu">跳</a>
        </div>
        <div class="collapse" role="tabpanel" id="jump-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
            <%= render "users/menu_index_part", :menus => @menus_jump %>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#throw-menu" role="button" aria-expanded="false" aria-controls="throw-menu">投</a>
        </div>
        <div class="collapse" role="tabpanel" id="throw-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
            <%= render "users/menu_index_part", :menus => @menus_throw %>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#drill-menu" role="button" aria-expanded="false" aria-controls="drill-menu">補強・サーキット</a>
        </div>
        <div class="collapse" role="tabpanel" id="drill-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
            <%= render "users/menu_index_part", :menus => @menus_drill %>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-secondary font-weight-bold" role="tab">
            <a class="text-body text-white" data-toggle="collapse" href="#other-menu" role="button" aria-expanded="false" aria-controls="other-menu">その他</a>
        </div>
        <div class="collapse" role="tabpanel" id="other-menu" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
            <%= render "users/menu_index_part", :menus => @menus_other %>
        </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-show-body">
  <%= render "users/user_header", :user => @user, :diaries => get_diaries(@user) %>
  <%= render "users/user_nav", :user => @user %>
  <div class="user-notice div-center">
    <div class="timeline-area div-center">
      <%= render "users/timeline", :notices => @notices %>
    </div>
  </div>

  <div class="my-pagenate w-75 clearfix">
    <div class="float-left">
      <%= render "page_counter", :models => @notices %>
    </div>
    <div class="float-right">
      <%= paginate @notices %>
    </div>
  </div>
</div>

app/views/users/unregist_confirm.html.erb
<h2>退会について</h2>

<div class="unregist_confirm">
    <ul>
        <li class="text-danger">
            <strong>退会後はアカウントにアクセスできなくなります</strong>
        </li>
        <li>
            グループリーダーとなっている場合は、<br>
            <strong>リーダー権限を移譲</strong>してから退会してください
        </li>
    </ul>
    <p>
        本当に退会する場合はパスワードを入力し、<br>
        「退会」ボタンを押してください
    </p>
    <%= form_tag unregist_users_path do %>
        <div class="field">
            <%= label_tag :password, "パスワード" %><br>
            <%= password_field_tag :password %>
        </div>
        <%= submit_tag "退会", :class => "btn btn-danger" %>
    <% end %>
</div>