config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  
  get 'home/top'
  get 'home/tfdiary'
  get 'home/terms'
  get 'home/questions'

  devise_for :users, :skip => [:registration], controllers: {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  resources :users, :only => [:show] do
    collection do
      patch :change_image
      get :follow_menu
      get :unfollow_menu
      get :follow_user
      get :unfollow_user
      get :follow_diary
      get :unfollow_diary
      get :unregist_confirm
      post :unregist
    end
    
    member do
      get :follow_index
      get :follower_index
      get :menu_index
      get :group_index
      get :regist_menu
      get :set_main_group
    end
    
    resources :diaries, shallow: true do
      collection do
        post :save_diary_all
        get :add_all_menu
        post :regist_menus
        post :save_diary_group
        get :select_group_menu
        get :read_group_menu
      end
      
      member do
        get :favoriter_index
      end
      
      resources :comments, :only => [:create, :destroy]
    end
  end

  resources :menus do
    collection do
      get :search
    end
    
    member do
      get :register_index
    end
  end

  resources :groups do
    collection do
      get :search
    end
    
    member do
      post :follow
      patch :follow_cancel
      patch :change_image
    end
    
    resources :group_member, :only => [:index], shallow: true do
      member do
        get :top
        get :setting
        get :menu_status
        get :request_index
        post :post_chat
        get :delete_chat
        get :assign_job
        patch :change_job
        post :follow_approve
        post :follow_reject
        get :unfollow_confirm
        get :unfollow
      end
    end
    
    resources :group_diaries do
      collection do
        post :add_all_menu
        post :regist_menus
      end
    end
  end

  get 'contacts/input'
  post 'contacts/confirm'
  post 'contacts/send_msg'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def check_login
    if !(view_context.logged_in?)
      redirect_to home_login_form_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def simple_time(time)
        time.strftime("%Y-%m-%d %H:%M")
    end
    
    def active?(controller, action)
        return "active" if (controller == params[:controller]) && (action == params[:action])
    end
    
    def active_action?(action_name)
        return "active" if action_name == params[:action]
    end
end

app/views/application/_footer.html.erb
<footer class="fixed-bottom bg-info text-white">
  <div class="footer-content">
    <nav>
      <ul>
        <li class="footer-link">
          <%= link_to "利用規約", home_terms_path, :class => "text-white" %>
        </li>
        <li class="footer-link">
          <%= link_to "よくあるご質問", home_questions_path, :class => "text-white" %>
        </li>
        <li class="footer-link">
          <%= link_to "お問い合わせ", contacts_input_path, :class => "text-white" %>
        </li>
        <% if user_signed_in? %>
          <li class="footer-link">
            <%= link_to "退会について", unregist_confirm_users_path, :class => "text-white" %>
          </li>
        <% end %>
      </ul>
    </nav>
    <div class="copy-right">
      © 2018 Hi Assist Service.
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-fixed-top justify-content-between fixed-top" style="background-color: #4169E1;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="Navbar">
        <% if !(user_signed_in?) %>
          <%= link_to "TFDiary", root_path, class:"navbar-brand nav-link" %>
          <ul class="navbar-nav navbar-right ml-auto">
              <!--ログインしているかどうかで分岐-->
              <li class="nav-item">
                <%= link_to "TFDiaryとは", home_tfdiary_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "メニュー検索", menus_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class:"nav-link" %>
              </li>
          </ul>
        <% else %>
          <%= link_to "TFDiary", user_path(current_user.id), class:"navbar-brand nav-link" %>
          <ul class="navbar-nav navbar-right ml-auto">
            <li class="nav-item dropdown">
              <%= link_to current_user.name, '#', data: {toggle:"dropdown"}, class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLink", 'aria-haspopup': "true", 'aria-expanded': "false"%>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "個人ページ", user_path(current_user.id), class:"dropdown-item" %>
                <%= link_to "日誌作成", new_user_diary_path(current_user.id), class:"dropdown-item"  %>
                <%= link_to "ログアウト", destroy_user_session_path, method: "DELETE", class:"dropdown-item", class:"dropdown-item"  %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "グループ検索", groups_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "メニュー検索", menus_path, class:"nav-link" %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
</header>

app/views/application/_notice.html.erb
<div class="notice">
<% if notice %>
    <p class="alert alert-dismissible alert-success"><%= notice %></p>
<% end %>

<% if alert %>
    <p class="alert alert-dismissible alert-danger"><%= alert %></p>
<% end %>
</div>

app/views/application/_page_counter.html.erb
<% if 0 == models.length %>
    <%= models.offset_value %>ー<%= models.offset_value + models.length %>件表示
<% else %>
    <%= models.offset_value + 1 %>ー<%= models.offset_value + models.length %>件表示
<% end %>
&ensp; / &ensp;
全体<%= models.total_count %>件