config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  
  get 'home/top'
  get 'home/tfdiary'
  get 'home/terms'
  get 'home/questions'

  devise_for :users, :skip => [:registration], controllers: {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  resources :users, :only => [:show] do
    collection do
      patch :change_image
      get :follow_menu
      get :unfollow_menu
      get :follow_user
      get :unfollow_user
      get :follow_diary
      get :unfollow_diary
      get :unregist_confirm
      post :unregist
    end
    
    member do
      get :follow_index
      get :follower_index
      get :menu_index
      get :group_index
      get :regist_menu
      get :set_main_group
    end
    
    resources :diaries, shallow: true do
      collection do
        post :save_diary_all
        get :add_all_menu
        post :regist_menus
        post :save_diary_group
        get :select_group_menu
        get :read_group_menu
      end
      
      member do
        get :favoriter_index
      end
      
      resources :comments, :only => [:create, :destroy]
    end
  end

  resources :menus do
    collection do
      get :search
    end
    
    member do
      get :register_index
    end
  end

  resources :groups do
    collection do
      get :search
    end
    
    member do
      post :follow
      patch :follow_cancel
      patch :change_image
    end
    
    resources :group_member, :only => [:index], shallow: true do
      member do
        get :top
        get :setting
        get :menu_status
        get :request_index
        post :post_chat
        get :delete_chat
        get :assign_job
        patch :change_job
        post :follow_approve
        post :follow_reject
        get :unfollow_confirm
        get :unfollow
      end
    end
    
    resources :group_diaries do
      collection do
        post :add_all_menu
        post :regist_menus
      end
    end
  end

  get 'contacts/input'
  post 'contacts/confirm'
  post 'contacts/send_msg'

end

app/controllers/group_member_controller.rb
class GroupMemberController < ApplicationController
  before_action :group_delete_check
  before_action :authenticate_user!
  before_action :check_group_member, except: [:index]
  before_action :check_group_member_index, only: [:index]
  before_action :check_admin_user, only: [:setting, :request_index, :follow_approve, :follow_reject, :assign_job, :change_job]
  
  def top
    @group = Group.find(params[:id])
    @chats = @group.chats.order(created_at: :desc).page(params[:page]).per(20)
    @chat = @group.chats.build
  end

  def index
    @group = Group.find(params[:group_id])
    @members = @group.user_followers.page(params[:page]).per(20)
  end

  def menu_status
    # メニュー達成率の機能追加予定
    @group = Group.find(params[:id])
  end
  
  def change_image
    @group = Group.find(params[:id])
    @group.image = params[:group][:image]
    @group.save
    redirect_to top_group_member(@group.id)
  end
  
  def post_chat
    @group = Group.find(params[:id])
    @chat = @group.chats.build(chat_params)
    if @chat.save
      create_chat_notice(@group)
      redirect_to top_group_member_path(@group.id)
    else
      render :top
    end
  end
  
  def delete_chat
    @group = Group.find(params[:id])
    @chat = Chat.find(params[:chat_id])
    @chat.destroy
    redirect_to top_group_member_path(@group.id)
  end
  
  def setting
    @group = Group.find(params[:id])
  end
  
  def request_index
    @group = Group.find(params[:id])
    @requests = @group.group_requests.page(params[:page]).per(20)
  end

  def assign_job
    @group = Group.find(params[:id])
    @members = @group.user_followers
  end
  
  def change_job
    @group = Group.find(params[:id])
    @group.update(change_job_params)
    redirect_to assign_job_group_member_path(@group.id)
  end
  
  def follow_approve
    group = Group.find(params[:id])
    user = User.find(params[:user_id])
    create_addmember_notice(group, user)
    user.follow(group)
    group.group_requests.find_by(user_id: user.id).destroy
    redirect_to request_index_group_member_path(group.id)
  end

  def follow_reject
    group = Group.find(params[:id])
    user = User.find(params[:user_id])
    group.group_requests.find_by(user_id: user.id).destroy
    redirect_to request_index_group_member_path(group.id)
  end
  
  def unfollow_confirm
    @group = Group.find(params[:id])
  end

  def unfollow
    group = Group.find(params[:id])
    view_context.current_user.stop_following(group)
    redirect_to group_index_user_path(view_context.current_user.id)
  end

private
  def chat_params
    params.require(:chat).permit(:user_id, :content)
  end

  def group_delete_check
    unless Group.find_by(id: params[:id]) || Group.find_by(id: params[:group_id])
      flash[:alert] = "グループが存在しません"
      redirect_to root_path
    end
  end

  def check_group_member
    if !view_context.current_user.following?(Group.find(params[:id]))
      redirect_to group_path(params[:id])
    end
  end

  def check_group_member_index
    if !view_context.current_user.following?(Group.find(params[:group_id]))
      redirect_to root_path
    end
  end

  def check_admin_user
    if !view_context.admin_user?(params[:id], view_context.current_user.id)
      redirect_to top_group_member_path(params[:id])
    end
  end
  
  def change_job_params
    params.require(:group).permit(:leader_id, :subleader_id1, :subleader_id2, :subleader_id3, :manager_id1, :manager_id2)
  end
  
  # メンバ追加通知
  def create_addmember_notice(group, user)
    group.user_followers.each do |member|
      latest = member.notices.order(created_at: :desc).first
      notice = member.notices.build()
      notice.create_group_addmember(group, user.name, group_group_member_index_path(group.id))
      unless latest&.msg == notice.msg
        notice.save
      end
    end
  end

  # チャット投稿通知
  def create_chat_notice(group)
    group.user_followers.each do |member|
      latest = member.notices.order(created_at: :desc).first
      notice = member.notices.build()
      notice.create_group_chat(group, top_group_member_path(group.id))
      unless latest&.msg == notice.msg
        notice.save
      end
    end
  end
end

app/helpers/group_member_helper.rb
module GroupMemberHelper
  def get_diaries_group(group)
    group.diaries.where(:date => Time.now.strftime("%Y-%m-%d"))
  end
  
  def active_setting?
    return "active" if ("setting" == params[:action]) || ("edit" == params[:action]) || ("assign_job" == params[:action]) || ("new" == params[:action])
  end
end

app/views/group_member/_chat.html.erb
<div class="chat">
    <div class="chat-user">
        <% user = get_user(chat.user_id) %>
        <%= image_tag user.image, :size => "10x10" %>
        &emsp;
        <%= link_to user.name, user_path(user.id) %>
        &emsp;
        <%= simple_time(chat.updated_at) %>
        &emsp;
        <% if chat.user_id == current_user.id %>
            <%= link_to "削除", :controller => "group_member", :action => "delete_chat", :chat_id => chat.id %>
        <% end %>
    </div>
    <div class="chat-content">
        <%= simple_format(chat.content) %>
    </div>
</div>

app/views/group_member/_group_header.html.erb
<div class="group-member-top clearfix">
  <div class="group-member-left float-left">
    <div class="group-member-image">
      <% if admin_user?(group.id, current_user.id) %>
        <%= form_for group, :url => change_image_group_path(group.id), :html => {method: 'PATCH'} do |f| %>
          <%= f.label :image, :class => "ignore" %>
          <label for="group_image" class="image-select">
            <%= image_tag group.image, :size => "150x150" %>
            <%= f.file_field :image, :class => "ignore" %>
          </label>
        <% end %>
        <script type="text/javascript">
          $('input[type=file]').on('change', function (e) {
            console.log(e.target.files);
            if (e.target.files[0].size > 0) {
              $(this).parents('form').submit();
            }
          });
        </script>
      <% else %>
        <%= image_tag group.image, :size => "150x150" %>
      <% end %>
    </div>
    <div class="group-member-name">
      グループ：<%= group.name %>
    </div>
  </div>

  <div class="group-member-right float-left">
    <div class="group-member-target">
      グループ目標
      <div class="group-member-target-box">
        <%= simple_format(@group.target) %>
      </div>
    </div>
    <div class="group-member-todaymenu">
      今日のメニュー
      <div class="group-member-todaymenu-box text-center">
        <% if diaries.count == 0 %>
          登録無し
        <% end %>
        <% diaries.each do |diary| %>
          <div class="group-todaymenu">
            <%= link_to diary.title, group_group_diary_path(group.id, diary.id) %>
            <%= render "diaries/show_menu", diary: diary %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/group_member/_group_nav.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "チャット", top_group_member_path(group.id), :class => "nav-link #{active_action?('top')}" %>
  </li>
  <li class="nav-item">
    <%= link_to "メンバ一覧", group_group_member_index_path(group.id), :class => "nav-link #{active?('group_member', 'index')}" %>
  </li>
  <li class="nav-item">
    <%= link_to "練習メニュー", group_group_diaries_path(group.id), :class => "nav-link #{active?('group_diaries', 'index')}" %>
  </li>
  <li class="nav-item">
    <%= link_to "メニュー達成状況", menu_status_group_member_path(group.id), :class => "nav-link #{active_action?('menu_status')}" %>
  </li>
  <% if admin_user?(group.id, current_user.id) %> 
    <li class="nav-item">
      <%= link_to "加入申請", request_index_group_member_path(group.id), :class => "nav-link #{active_action?('request_index')}" %>
    </li>
    <li class="nav-item">
      <%= link_to "設定", setting_group_member_path(group.id), :class => "nav-link #{active_setting?}" %>
    </li>
  <% end %>
</ul>

app/views/group_member/_job.html.erb
<% case member.id %>
<% when group.leader_id then %>
    リーダー
<% when group.subleader_id1, group.subleader_id2, group.subleader_id3 then %>
    サブリーダー
<% when group.manager_id1, group.manager_id2 then %>
    マネージャー
<% else %>
    <!--処理なし-->
<% end %>

app/views/group_member/_job_button.html.erb
<% if !admin_user?(group.id, member.id) %>
    <div class="assign-leader">
        <% if current_user.id == group.leader_id %>
            <%= form_for group, :url => {:action => 'change_job'} do |f| %>
                <%= f.hidden_field :leader_id, :value => member.id %>
                <%= f.submit "リーダー", :class => "btn btn-primary assign-btn", :data => {:confirm => "リーダー権限を移譲します。よろしいですか？"} %>
            <% end %>
        <% else %>
            <div class="btn btn-default disabled assign-btn" onClick="alert('リーダー設定できるのはリーダーのみです')">
                リーダー設定
            </div>
        <% end %>
    </div>

    <div class="assign-subleader">
        <%= form_for group, :url => {:action => 'change_job'} do |f| %>
            <% if !group.subleader_id1 %>
                <%= f.hidden_field :subleader_id1, :value => member.id %>
                <%= f.submit "サブリーダー", :class => "btn btn-primary assign-btn" %>
            <% elsif !group.subleader_id2 %>
                <%= f.hidden_field :subleader_id2, :value => member.id %>
                <%= f.submit "サブリーダー", :class => "btn btn-primary assign-btn" %>
            <% elsif !group.subleader_id3 %>
                <%= f.hidden_field :subleader_id3, :value => member.id %>
                <%= f.submit "サブリーダー", :class => "btn btn-primary assign-btn" %>
            <% else %>
                <div class="btn btn-default disabled assign-btn" onClick="alert('サブリーダーは3人までです')">
                    サブリーダー
                </div>
            <% end %>
        <% end %>
    </div>
    
    <div class="assign-manager">
        <%= form_for group, :url => {:action => 'change_job'} do |f| %>
            <% if !group.manager_id1 %>
                <%= f.hidden_field :manager_id1, :value => member.id %>
                <%= f.submit "マネージャー", :class => "btn btn-primary assign-btn" %>
            <% elsif !group.manager_id2 %>
                <%= f.hidden_field :manager_id2, :value => member.id %>
                <%= f.submit "マネージャー", :class => "btn btn-primary assign-btn" %>
            <% else %>
                <button type="button" class="btn btn-primary assign-btn" onClick="alert('マネージャーは2人までです')">
                    マネージャー
                </button>
            <% end %>
        <% end %>
    </div>
<% else %>
    <% if member.id == group.leader_id %>
        &emsp;リーダーの方の権限操作はできません。
    <% end %>
    
    <% if member.id == group.subleader_id1 %>
        <%= form_for group, :url => {:action => 'change_job'} do |f| %>
            <%= f.hidden_field :subleader_id1, :value => nil %>
            <%= f.submit "権限削除", :class => "btn btn-danger assign-btn" %>
        <% end %>
    <% elsif member.id == group.subleader_id2 %>
        <%= form_for group, :url => {:action => 'change_job'} do |f| %>
            <%= f.hidden_field :subleader_id2, :value => nil %>
            <%= f.submit "権限削除", :class => "btn btn-danger assign-btn" %>
        <% end %>
    <% elsif member.id == group.subleader_id3 %>
        <%= form_for group, :url => {:action => 'change_job'} do |f| %>
            <%= f.hidden_field :subleader_id3, :value => nil %>
            <%= f.submit "権限削除", :class => "btn btn-danger assign-btn" %>
        <% end %>
    <% end %>
    
    <% if member.id == group.manager_id1 %>
        <%= form_for group, :url => {:action => 'change_job'} do |f| %>
            <%= f.hidden_field :manager_id1, :value => nil %>
            <%= f.submit "権限削除", :class => "btn btn-danger assign-btn" %>
        <% end %>
    <% elsif  member.id == group.manager_id2 %>
        <%= form_for group, :url => {:action => 'change_job'} do |f| %>
            <%= f.hidden_field :manager_id2, :value => nil %>
            <%= f.submit "権限削除", :class => "btn btn-danger assign-btn" %>
        <% end %>
    <% end %>
<% end %>

app/views/group_member/_return_link.html.erb
<div class="return_to_group_top">
    <%= link_to "グループトップへ", top_group_member_path(id) %>
</div>

app/views/group_member/_submit_delete.html.erb
<% if current_user.id == member_id %>
    <%= f.submit "権限削除", :class => "btn btn-danger assign-btn", :data => {:confirm => "権限削除するとグループ設定にアクセスできなくなります。よろしいですか？"} %>
<% else %>
    <%= f.submit "権限削除", :class => "btn btn-danger assign-btn" %>
<% end %>

app/views/group_member/assign_job.html.erb
<div class="group-member">
  <%= render "group_member/group_header", :group => @group, :diaries => get_diaries_group(@group) %>
  <%= render "group_member/group_nav", :group => @group %>

  <div class="group-contents">
    <div id="member-index">
      <% @members.each do |member| %>
        <div class="member-user">
          <div class="float-left">
            <%= image_tag member.image, :size => "50x50" %>
          </div>
          <div class="float-left">
          <div class="member-name float-left">
            <%= link_to member.name, user_path(member.id) %>
          </div>
          <div class="member-job float-left">
            <%= render "group_member/job", :member => member, :group => @group %>
          </div>
          <div class="member-button">
            <%= render "group_member/job_button", :member => member, :group => @group %>
          </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/group_member/index.html.erb
<div class="group-member">
  <%= render "group_member/group_header", :group => @group, :diaries => get_diaries_group(@group) %>
  <%= render "group_member/group_nav", :group => @group %>

  <div class="group-contents">
    <div id="member-index">
        <% @members.each do |member| %>
            <div class="member-user">
                <%= image_tag member.image, :size => "50x50" %>
                &emsp;
                <%= link_to member.name, user_path(member.id) %>
                &emsp;
                <%= render "group_member/job", :member => member, :group => @group %>
            </div>
        <% end %>
    </div>
    <div class="my-pagenate w-50 clearfix">
      <div class="float-left">
        <%= render "page_counter", :models => @members %>
      </div>
      <div class="float-right">
        <%= paginate @members %>
      </div>
    </div>
  </div>
</div>

app/views/group_member/menu_status.html.erb
<div class="group-member">
  <%= render "group_member/group_header", :group => @group, :diaries => get_diaries_group(@group) %>
  <%= render "group_member/group_nav", :group => @group %>

  <div class="group-contents">
    <div class="menu-status">
      <%= image_tag asset_path("icon/kojichu.png"), :size => "100x100" %>
      <br>
      今後のアップデートで実装予定です。お楽しみに！
    </div>
  </div>
</div>

app/views/group_member/request_index.html.erb
<div class="group-member">
  <%= render "group_member/group_header", :group => @group, :diaries => get_diaries_group(@group) %>
  <%= render "group_member/group_nav", :group => @group %>

  <div class="group-contents">
    <div id="member-index">
      <% @requests.each do |req| %>
        <div class="member-user">
          <% user = get_user(req.user_id) %>
          <%= image_tag user.image, :size => "50x50" %>
          &emsp;
          <%= link_to user.name, user_path(user.id) %>
          &emsp;
          <%= link_to "承認", follow_approve_group_member_path(@group.id, :user_id => user.id), :method => "POST", :class => "btn btn-primary" %>
          &ensp;
          <%= link_to "拒否", follow_reject_group_member_path(@group.id, :user_id => user.id), :method => "POST", :class => "btn btn-danger" %>
        </div>
      <% end %>
    </div>
    <div class="my-pagenate w-75 clearfix">
      <div class="float-left">
        <%= render "page_counter", :models => @requests %>
      </div>
      <div class="float-right">
        <%= paginate @requests %>
      </div>
    </div>
  </div>
</div>

app/views/group_member/setting.html.erb
<div class="group-member">
  <%= render "group_member/group_header", :group => @group, :diaries => get_diaries_group(@group) %>
  <%= render "group_member/group_nav", :group => @group %>

  <div class="group-contents">
    <div class="list-group w-75 mx-auto">
      <%= link_to "グループ情報を更新", edit_group_path(@group.id), :class => "list-group-item list-group-item-action" %>
      <%= link_to "JOB割り当て", assign_job_group_member_path(@group.id), :class => "list-group-item list-group-item-action" %>
      <%= link_to "グループ練習メニュー作成", new_group_group_diary_path(@group.id), :class => "list-group-item list-group-item-action" %>
      <% if @group.leader_id == current_user.id %>
        <%= link_to "グループ削除", group_path(@group.id), :method => "DELETE", :class => "list-group-item list-group-item-action", :data => {:confirm => "メニューやチャットが全て削除されます。本当によろしいですか？"} %>
      <% end %>
    </div>
  </div>
</div>

app/views/group_member/top.html.erb
<div class="group-member">
  <%= render "group_member/group_header", :group => @group, :diaries => get_diaries_group(@group) %>
  <%= render "group_member/group_nav", :group => @group %>

  <div class="group-contents">
    <div class="group-chat clearfix">
      <div class="group-chat-post mx-auto float-left">
        <%= form_for @chat, :url => {:action => "post_chat"} do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.text_area :content, :size => "40×5", :class => "form-control" %>
          <div class="chat-post">
            <%= f.submit "投稿", :class => "btn btn-outline-primary" %>
          </div>
        <% end %>
      </div>
      <div class="group-chat-index mx-auto float-left">
        <ul class="list-group">
        <% if @chats.count == 0 %>
          <li class="list-group-item">チャットの投稿はまだありません</li>
        <% else %>
          <% @chats.each do |chat| %>
            <% if chat.id != @chat.id %>
              <li class="list-group-item"><%= render "group_member/chat", {chat: chat} %></li>
            <% end %>
          <% end %>
        <% end %>
        </ul>
        <div class="my-pagenate w-75 clearfix">
          <div class="float-left">
            <%= render "page_counter", :models => @chats %>
          </div>
          <div class="float-right">
            <%= paginate @chats %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/group_member/unfollow_confirm.html.erb
<h2><%= @group.name %>から脱退</h2>

<div class="group-unfollow-confirm">
    <% if current_user.id == @group.leader_id %>
        あなたは<strong>リーダー</strong>の為、グループから脱退することが出来ません。<br>
        リーダー権限を移譲するか、他にメンバがいない場合は<br>
        グループを削除して下さい<br>
        <div class="group-unfollow-link">
            <%= link_to "グループトップへ", top_group_member_path(@group.id) %>
            &emsp;
            <%= link_to "所属グループ一覧へ", group_index_user_path(current_user.id) %>
        </div>
    <% else %>
        グループへ再加入するには、グループ管理者からの承認を得る必要があります。<br>
        本当によろしいですか。<br>
        <div class="group-unfollow-link">
            <%= link_to "グループ一覧へ戻る", group_index_user_path(current_user.id) %>
            &emsp;
            <%= link_to "グループから脱退", unfollow_group_member_path(@group.id) %>
        </div>
    <% end %>
</div>